version: '3.8'

services:

  client-backend:
    image: client:0.0.1
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - postgres
      - redis
    environment:
      - "SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/re_service_db"
      - "SPRING_DATASOURCE_USERNAME=postgres"
      - "SPRING_DATASOURCE_PASSWORD=qwerty123"
      - MINIO_ACCESS_KEY=78umrpzruUvWfBk5pHjm
      - MINIO_SECRET_KEY=xIe0IR1aRybTxsuOnmTREAJA8RsmIaj9cCpSpbBh

  postgres:
    container_name: postgres-re-service
    image: postgres:12-alpine
    restart: on-failure
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: qwerty123
      POSTGRES_DB: re_service_db
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"

  redis:
    container_name: redis-re-service
    image: redis:6.2-alpine
    ports:
      - "6379:6379"
    command: redis-server --save 60 1 --appendonly yes --appendfsync everysec>
    environment:
      REDIS_PASSWORD: qwerty456
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"

volumes:
  pgdata:
  redis-volume: