openapi: 3.0.3
info:
  title: API для работы с аккаунтом
  description: API для работы с аккаунтом
  version: 1.0.0
servers:
  - url: https://localhost:8080/api/v1
tags:
  - name: Account
    description: API для работы с аккаунтом
paths:
  /account:
    get:
      summary: Получение всех аккаунтов
      operationId: getAccounts
      tags:
        - Account
      responses:
        '200':
          description: '200'
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: 'Components.yaml#/components/schemas/accountDto'
        '400':
          description: '400'
        '403':
          description: '403'
        '404':
          description: '404'
        '500':
          description: '500'
  /account/{id}:
    get:
      summary: Получение аккаунта по id
      operationId: getAccountById
      tags:
        - Account
      parameters:
        - name: id
          in: path
          schema:
            type: string
            format: uuid
          required: true
      responses:
        '200':
          description: '200'
          content:
            application/json:
              schema:
                $ref: 'Components.yaml#/components/schemas/accountDto'
        '400':
          description: '400'
        '403':
          description: '403'
        '404':
          description: '404'
        '500':
          description: '500'
  /account/{id}/appointAdmin:
    post:
      summary: Назначить админом пользователя
      operationId: appointAdmin
      tags:
        - Account
      parameters:
        - name: id
          in: path
          description: "Id пользователя"
          schema:
            type: string
            format: uuid
          required: true
      responses:
        '200':
          description: '200'
          content:
            application/json:
              schema:
                $ref: 'Components.yaml#/components/schemas/accountDto'
        '400':
          description: '400'
        '403':
          description: '403'
        '404':
          description: '404'
        '500':
          description: '500'
  /account/token:
    get:
      summary: Получение пользователя по accessToken
      operationId: getAccountByToken
      tags:
        - Account
      parameters:
        - name: Authorization
          in: header
          description: "Access token"
          schema:
            type: string
      responses:
        '200':
          description: '200'
          content:
            application/json:
              schema:
                $ref: 'Components.yaml#/components/schemas/accountDto'
        '400':
          description: '400'
        '403':
          description: '403'
        '404':
          description: '404'
        '500':
          description: '500'


