openapi: 3.0.3
info:
  title: API для работы c аутентификацией, регистрацией и получением токенов
  description: API для работы c аутентификацией, регистрацией и получением токенов
  version: 1.0.0
servers:
  - url: https://localhost:8080/api/v1
tags:
  - name: Auth
    description: API для работы c аутентификацией, регистрацией и получением токенов
paths:
  /auth/signUp:
    post:
      summary: Регистрация
      operationId: signUp
      tags:
        - Auth
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/signUpDto'
      responses:
        '200':
          description: '200'
          content:
            application/json:
              schema:
                $ref: 'Components.yaml#/components/schemas/accountDto'
        '400':
          description: '400'
        '403':
          description: '403'
        '404':
          description: '404'
        '500':
          description: '500'
  /auth/signIn:
    post:
      summary: Авторизация
      operationId: signIn
      tags:
        - Auth
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/authDto'
      responses:
        '200':
          description: '200'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/jwtDto'
        '400':
          description: '400'
        '403':
          description: '403'
        '404':
          description: '404'
        '500':
          description: '500'
  /auth/refresh-token:
    post:
      summary: Обновление access и refresh токенов
      operationId: refreshToken
      tags:
        - Auth
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/refreshDto'
      responses:
        '200':
          description: '200'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/jwtDto'
        '400':
          description: '400'
        '403':
          description: '403'
        '404':
          description: '404'
        '500':
          description: '500'
components:
  schemas:
    signUpDto:
      type: object
      description: Модель регистрации пользователя
      required:
        - email
        - password
        - fullName
      properties:
        email:
          type: string
          format: email
          description: "Email"
        password:
          type: string
          description: "Пароль"
        fullName:
          type: string
          description: "Полное имя пользователя или ник"
    authDto:
      type: object
      description: Модель авторизации
      required:
        - email
        - password
      properties:
        email:
          type: string
          format: email
          description: "Email"
        password:
          type: string
          description: "Пароль"
    jwtDto:
      type: object
      description: Модель токена
      properties:
        accessToken:
          type: string
          description: "Access token"
        refreshToken:
          type: string
          description: "Refresh token"
    refreshDto:
      type: object
      description: Модель передачи refreshToken
      properties:
        refreshToken:
          type: string
          description: "Refresh token"






  
