openapi: 3.0.3
info:
  title: API для работы с файлами
  description: API для работы с файлами
  version: 1.0.0
servers:
  - url: https://localhost:8080/api/v1
tags:
  - name: File
    description: API для работы с файлами
paths:
  /file:
    post:
      summary: Загрузка файла
      operationId: uploadFile
      tags:
        - Keyword
      security:
        - bearerAuth: [ ]
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
      responses:
        '200':
          description: '200'
          content:
            application/json:
              schema:
                description: "Имя файла"
                type: string
        '400':
          description: '400'
        '403':
          description: '403'
        '404':
          description: '404'
        '500':
          description: '500'
    get:
      summary: Получение файла по filename
      operationId: getFile
      tags:
        - File
      parameters:
        - name: filename
          description: "Имя файла"
          in: query
          schema:
            type: string
          required: true
      responses:
        '200':
          description: '200'
          content:
            application/json:
              schema:
                type: string
                format: binary
                description: "Файл"
        '400':
          description: '400'
        '403':
          description: '403'
        '404':
          description: '404'
        '500':
          description: '500'
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT  # optional, for documentation purposes only

  
