openapi: 3.0.3
info:
  title: API для работы с заявками
  description: API для работы с заявками
  version: 1.0.0
servers:
  - url: https://localhost:8080/api/v1
tags:
  - name: Request
    description: API для работы с авторами
paths:
  /request:
    get:
      summary: Получение заявок с необязательными критериями 'state' и 'type'
      operationId: getRequests
      tags:
        - Request
      parameters:
        - name: state
          in: query
          schema:
            type: string
          required: false
          description: "Необязательный поиск по состоянию IN_PROCESSING, APPROVED или REJECTED"
        - name: type
          in: query
          schema:
            type: string
          required: false
          description: "Необязательный поиск по состоянию AUTHOR или PUBLICATION"
      responses:
        '200':
          description: '200'
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: 'Components.yaml#/components/schemas/requestDto'
        '400':
          description: '400'
        '403':
          description: '403'
        '404':
          description: '404'
        '500':
          description: '500'
  /request/{id}:
    get:
      summary: Получение заявки по id
      operationId: getRequestById
      tags:
        - Request
      parameters:
        - name: id
          in: path
          schema:
            type: string
            format: uuid
          required: true
      responses:
        '200':
          description: '200'
          content:
            application/json:
              schema:
                $ref: 'Components.yaml#/components/schemas/requestDto'
        '400':
          description: '400'
        '403':
          description: '403'
        '404':
          description: '404'
        '500':
          description: '500'
  /request/account/{accountId}:
    get:
      summary: Получение заявок по id заявителя
      operationId: getRequestsByAccountId
      tags:
        - Request
      parameters:
        - name: accountId
          in: path
          schema:
            type: string
            format: uuid
          required: true
          description: "Id пользователем, которым была создана заявка"
      responses:
        '200':
          description: '200'
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: 'Components.yaml#/components/schemas/requestDto'
        '400':
          description: '400'
        '403':
          description: '403'
        '404':
          description: '404'
        '500':
          description: '500'
  /request/{id}/comment:
    post:
      summary: Написания комментария по заявке администратором
      operationId: comment
      tags:
        - Request
      security:
        - bearerAuth: [ ]
      parameters:
        - name: id
          in: path
          schema:
            type: string
            format: uuid
          required: true
          description: "Id заявки"
      requestBody:
        content:
          application/json:
            schema:
              description: "Комментарий"
              type: string
      responses:
        '200':
          description: '200'
          content:
            application/json:
              schema:
                $ref: 'Components.yaml#/components/schemas/requestDto'
        '400':
          description: '400'
        '403':
          description: '403'
        '404':
          description: '404'
        '500':
          description: '500'
  /request/{id}/approve:
    post:
      summary: Одобрение заявки администратором
      operationId: approve
      tags:
        - Request
      security:
        - bearerAuth: [ ]
      parameters:
        - name: id
          in: path
          schema:
            type: string
            format: uuid
          required: true
          description: "Id заявки"
      responses:
        '200':
          description: '200'
          content:
            application/json:
              schema:
                $ref: 'Components.yaml#/components/schemas/requestDto'
        '400':
          description: '400'
        '403':
          description: '403'
        '404':
          description: '404'
        '500':
          description: '500'
  /request/{id}/reject:
    post:
      summary: Отклонение заявки администратором
      operationId: reject
      tags:
        - Request
      security:
        - bearerAuth: [ ]
      parameters:
        - name: id
          in: path
          schema:
            type: string
            format: uuid
          required: true
          description: "Id заявки"
      responses:
        '200':
          description: '200'
          content:
            application/json:
              schema:
                $ref: 'Components.yaml#/components/schemas/requestDto'
        '400':
          description: '400'
        '403':
          description: '403'
        '404':
          description: '404'
        '500':
          description: '500'
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT  # optional, for documentation purposes only

